variables:
  http_proxy: $CODE_PROXY
  https_proxy: $CODE_PROXY
  no_proxy: "code.siemens-energy.com,127.0.0.1,localhost,.siemens-energy.com,artifactory.siemens-energy.com"
  HTTP_PROXY: $CODE_PROXY
  HTTPS_PROXY: $CODE_PROXY
  NO_PROXY: $no_proxy

stages:
  - build-base-container
  - build-sw360
  - upload-bom
  
sw360-build-container:
  stage: build-base-container
  image:
    name: gcr.io/kaniko-project/executor:v1.21.1-debug
    entrypoint: [""]  
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
     /kaniko/executor \
      --context "${CI_PROJECT_DIR}" \
      --build-arg "http_proxy=${http_proxy}" \
      --build-arg "https_proxy=${https_proxy}" \
      --build-arg "no_proxy=${no_proxy}" \
      --dockerfile "${CI_PROJECT_DIR}/siemens-energy/sw360dev.Dockerfile" \
      --destination "${CI_REGISTRY_IMAGE}:latest" 
  rules:
    - changes:
      - siemens-energy/sw360dev.Dockerfile
  

build-and-test:
  stage: build-sw360
  image: ${CI_REGISTRY_IMAGE}:latest
  variables:
    _JAVA_OPTIONS: '-Djdk.util.zip.disableZip64ExtraFieldValidation=true'
  script:
    - |
      mvn clean install --no-transfer-progress -P deploy \
        -Dhelp-docs=true -Dbase.deploy.dir=. -Dliferay.deploy.dir=${PWD}/deploy -Dbackend.deploy.dir=${PWD}/deploy/webapps -Drest.deploy.dir=${PWD}/deploy/webapps \
        -DRunComponentVisibilityRestrictionTest=false -DRunPrivateProjectAccessTest=false -DRunRestForceUpdateTest=false -DskipTests \
        -Dhttp.proxySet=true -Dhttp.proxyHost=$CODE_PROXY_HOST -Dhttp.proxyPort=$CODE_PROXY_PORT -Dhttp.nonProxyHosts=localhost|couchdb"